dist: trusty  
language: cpp
matrix:
  include:
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      before_install:
        - sudo apt-get install -y libboost-dev
        - sudo apt-get install -y libboost-system-dev
      before_script:
        - export CXX=g++-4.9
      script:
        - mkdir build
        - cd build
        - cmake ..
        - make -j 2
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      before_install:
        - sudo apt-get install -y libboost-dev
        - sudo apt-get install -y libboost-system-dev
      before_script:
        - export CXX=g++-5
      script:
        - mkdir build
        - cd build
        - cmake ..
        - make -j 2